export const FETCH_EMP_REQUEST = "FETCH_EMP_REQUEST";
export const FETCH_EMP_SUCCESS = "FETCH_EMP_SUCCESS";
export const FETCH_EMP_FAILURE = "FETCH_EMP_FAILURE";

export const DELETE_EMP_REQUEST = "DELETE_EMP_REQUEST";
export const DELETE_EMP_SUCCESS = "DELETE_EMP_SUCCESS";
export const DELETE_EMP_FAILURE = "DELETE_EMP_FAILURE";


export const ADD_EMP_REQUEST = "ADD_EMP_REQUEST";
export const ADD_EMP_SUCCESS = "ADD_EMP_SUCCESS";
export const ADD_EMP_FAILURE = "ADD_EMP_FAILURE";